# NumPy list/arrays


## Why numpy array are different from python list?

| Feature               | Python List                                      | NumPy Array                                           |
|-----------------------|--------------------------------------------------|--------------------------------------------------------|
| **Data Type**         | Can store mixed data types                       | Homogeneous – all elements must be of the same type    |
| **Performance**       | Slower for numerical operations                  | Faster due to optimized C implementation               |
| **Memory Usage**      | Higher memory usage                              | More memory-efficient                                  |
| **Functionality**     | Basic operations (append, remove, etc.)          | Rich set of mathematical and statistical operations    |
| **Indexing**          | Basic indexing and slicing                       | Advanced indexing, slicing, and broadcasting           |
| **Vectorized Ops**    | Not supported; requires loops                    | Fully supports vectorized operations                   |
| **Convenience**       | Flexible for general-purpose programming         | Ideal for numerical and matrix computations            |
| **Use Case**          | General-purpose container                        | Scientific computing, data analysis, machine learning  |



In [18]:
import numpy as np

#creating basic numpy array

python_list = [1,2,3,4,5,6]
np_array = np.array([1,2,3,4,5,6])

print(type(python_list),python_list)   # <class 'list'> [1, 2, 3, 4, 5, 6]
print(type(np_array),np_array) # <class 'numpy.ndarray'> [1 2 3 4 5 6]

<class 'list'> [1, 2, 3, 4, 5, 6]
<class 'numpy.ndarray'> [1 2 3 4 5 6]


In [19]:

# 2d Array
np_2DArr=np.array([[1,2,3],[4,5,6]])
print(type(np_array),np_2DArr)   # <class 'numpy.ndarray'> [[1 2 3][4 5 6]]

# Multi-diamensiona array
np_multiDiamArr=np.array([[[1,2],[2,3]],[[3,4],[1,3]]])
print(type(np_multiDiamArr),np_multiDiamArr) # <class 'numpy.ndarray'>  [[[1,2],[2,3]],[[3,4],[1,3]]]



<class 'numpy.ndarray'> [[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'> [[[1 2]
  [2 3]]

 [[3 4]
  [1 3]]]


In [22]:

# creating array with specific value only (Arrays.fill() in java)

np_array_zeros=np.zeros((2,4))   # we have to pass tuple (r,c) -> total numeber of row and columns 
print(np_array_zeros)    # [[0,0,0,0],[0,0,0,0]] -> all 2d array filled with zero (but type is float so you will see .)

np_array_ones= np.ones((3,2))
print(np_array_ones)    # [[1,1],[1,1],[1,1]]

np_array_any =np.full((3,3),7)     # crate 3*3 array with all value as 7
print(np_array_any)

# By deafult data type is float for ones and zeros we can manage that by passing dtype=int
np_arr_zero_int=np.zeros((2,3),dtype=int)
print(np_arr_zero_int)

# similarly if we want specific type of data in matrix we can set it using dtype=x , where x is datatype
np_arr_string=np.full((3,2),"-")
print(np_arr_string)

np_empty_arr=np.empty((2, 2))  # non empty array default value is 0
print(np_empty_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0 0 0]
 [0 0 0]]
[['-' '-']
 ['-' '-']
 ['-' '-']]
[[0. 0.]
 [0. 0.]]


In [27]:

# An identity matrix is a square matrix with ones on the main diagonal (from the top-left to the bottom-right) and zeros everywhere else
# This identity matrix is used to solve some liner equation and used in Matrix Multiplication Identity.
# Just understand what is does application will be used later in math notes.
np_identity_matrix=np.eye(3)
print(np_identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:

# Create array between range 

np_range_arr=np.arange(1,15,2)  # create array from range (start ,end(excluding) , jump/skip)   
print(np_range_arr)             # [ 1  3  5  7  9 11 13] 

[ 1  3  5  7  9 11 13]


In [ ]:
np_divide_with_even_space=np.linspace(0,10,10)    # (start, end ,total number of elements) -> divide the range evenly
print(np_divide_with_even_space)   # (s,e,t) -> will create t numbers between s to e (inclusive) with even space between each element

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [ ]:
# There is class called random in numpy package which helps to create n*m array with random values
#  np.random.randint(start,end,(n,m))  
np_random_arr=np.random.randint(0,10,(3,2))
print(np_random_arr)

# to create random n*m array of diff datatype some logic should be implemented 
# also we can have random array based on customization and use 'np.array([logic()])' to create array 

[[0 9]
 [4 0]
 [1 4]]
