# Some of the important concept regarding numpy array

In [14]:
import numpy as np


arr = np.array([10, 20, 30, 40, 50])

arr2d = np.array([[1, 2, 3], [4, 5, 6]])


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])




In [15]:

# 1. INDEXING IN NUMPY -Indexing means accessing individual elements of an array.

print(arr[0]) # 10
print(arr[-1]) # 50 (negative indexing is also supported (-1 to n))

print(arr2d[0, 1]) # 2 ( for multidiamnesional array give (r,c))
print(arr2d[1,-1]) # 6 (also supports negative index)

10
50
2
6


In [16]:
# 2.SLICING - Slicing lets you extract a portion of an array.

# overview -> pass [start:end] in array and will give you elements in that range
# end is excluded so if you pass arr[1:4] ,it will give you elements from index (1) to (4-1=3)
# if you keep either start or end as empty, it will consider max range is possible on that side which is (0,n-1)
# pass third parameter to jump in range 

print(arr[1:4])   # [20 30 40] 
print(arr[:3])    # [10 20 30]
print(arr[::2])   # [10 30 50]
print(arr[::-1])  # [50 40 30 20 10] Used for reversing the array (jump is -1)


[20 30 40]
[10 20 30]
[10 30 50]
[50 40 30 20 10]


In [18]:

# 3.Basic Mathematical Functions


print(a + b)  # [5 7 9]
print(a - b)  # [-3 -3 -3]
print(a * b)  # [4 10 18]
print(a / b)  # [0.25 0.4  0.5 ]



[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [20]:
# 4.Other 


x = np.array([1, 2, 3, 4])

print(np.sin(x))       # [0.84147098 0.90929743 0.14112001 -0.7568025]
print(np.cos(x))       # [0.54030231 -0.41614684 -0.9899925 -0.65364362]
print(np.tan(x))       # [1.55740772 -2.18503986 -0.14254654 1.15782128]

print(np.exp(x))       # [2.71828183 7.3890561 20.08553692 54.59815003]
print(np.log(x))       # [0. 0.69314718 1.09861229 1.38629436]
print(np.log10(x))     # [0. 0.30103 0.47712125 0.60205999]

print(np.power(x, 2))  # [1 4 9 16]
print(np.sqrt(x))      # [1. 1.41421356 1.73205081 2.]
 


[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]
[0.         0.30103    0.47712125 0.60205999]
[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]
