# BROADCASTING 

- Broadcasting allows NumPy to perform element-wise operations on arrays of different shapes without explicitly copying data.
- Instead of manually reshaping or looping, NumPy automatically expands the smaller array to match the shape of the larger one without actually copying data.


When operating on two arrays, NumPy compares their shapes element-wise from the trailing dimensions. Two dimensions are compatible when:

- They are equal, or
- One of them is 1

If the shapes are not compatible, NumPy throws a ValueError.

In [1]:

import numpy as np

a = np.array([1, 2, 3])
b = 10

print(a + b)  # [11 12 13]


[11 12 13]


In [2]:

a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

print(a + b)


[[11 22 33]
 [14 25 36]]


## why?

- No loops → faster execution
- Less memory usage → avoids unnecessary copies
- Cleaner code → more readable and concise